on:
    push:
        tags:
            - v*

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  submodules: true
            - name: Install Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 10.x
            - run: yarn install
            - run: yarn check
            - run: yarn pub publish --yarn --pat ${{ secrets.MARKETPLACE_TOKEN }}
